name: build-and-test
name: ROS 2 Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup ROS 2 (Humble)
        uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: humble

      - name: Install dependencies
        run: |
          sudo apt update
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build workspace
        run: |
          colcon build
          source install/setup.bash

      - name: Run tests
        run: |
          colcon test
          colcon test-result --verbose

